package com.project75.jpanels;

import com.project75.core.Semester;
import com.project75.core.Subject;

/**
 *
 * @author Aryan
 */
public class AllSubjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllSubjectPanel
     */
    
    
    private Semester sem;
    
    public AllSubjectPanel() {
        initComponents();
    }
    
    public AllSubjectPanel(Semester sem){
        initComponents();
        this.sem = sem;
        buildUI();
    }
    
    private void buildUI() {
        setLayout(new java.awt.GridLayout(0, 2, 15, 15));

        Subject[] subs = sem.getSubs();

        for (Subject s : subs) {
            SubjectPanel sp = new SubjectPanel(s);
            add(sp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(660, 528));
        setMinimumSize(new java.awt.Dimension(660, 528));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
