package com.project75.jpanels;

import com.project75.core.Subject;

/**
 *
 * @author Aryan
 */
public class SubjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubjectPanel
     */
    
    private Subject subject;
    
    public SubjectPanel() {
        initComponents();
        subject = new Subject();
        updateVals();
    }
    
    
    public SubjectPanel(Subject subject){
        initComponents();
        this.subject = subject;
        updateVals();
    }
    
    public void updateVals(){
        labelSubjectName.setText("Subject: "+subject.getSubName());
        labelSubjectProfessor.setText("Professor: "+subject.getSubProfessor());
        labelSubjectCode.setText("Subject Code: "+subject.getSubId());
        int attendedLectures = subject.getAttendedLectures();
        int totalLectures = subject.getTotalLectures();
        int pcent = 0;
        try{
            pcent = (int)((attendedLectures * 100.0) / totalLectures);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        if(attendedLectures == -1){
            pcent = 0;
        }
        
        labelPercent.setText(Integer.toString(pcent));
        labelAttendedLectures.setText("Attended Lectures: "+ attendedLectures);
        labelTotalLectures.setText("Total Lectures: "+totalLectures);
        
        //  TODO: change color of the progress bar wrt to attendance percent
        
        progBarPercent.setValue(pcent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progBarPercent = new javax.swing.JProgressBar();
        labelPercent = new javax.swing.JLabel();
        labelSubjectName = new javax.swing.JLabel();
        labelSubjectCode = new javax.swing.JLabel();
        labelSubjectProfessor = new javax.swing.JLabel();
        labelAttendedLectures = new javax.swing.JLabel();
        labelTotalLectures = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        progBarPercent.setValue(69);

        labelPercent.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        labelPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPercent.setText("85");

        labelSubjectName.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelSubjectName.setText("Subject: Data Structures");

        labelSubjectCode.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelSubjectCode.setText("Professor: Anand Godbole");

        labelSubjectProfessor.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelSubjectProfessor.setText("Attended Lectures: 24");

        labelAttendedLectures.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelAttendedLectures.setText("Total Lectures: 32");

        labelTotalLectures.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelTotalLectures.setText("Subject Code: CE201");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progBarPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSubjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSubjectCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSubjectProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAttendedLectures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalLectures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSubjectProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAttendedLectures, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTotalLectures, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progBarPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAttendedLectures;
    private javax.swing.JLabel labelPercent;
    private javax.swing.JLabel labelSubjectCode;
    private javax.swing.JLabel labelSubjectName;
    private javax.swing.JLabel labelSubjectProfessor;
    private javax.swing.JLabel labelTotalLectures;
    private javax.swing.JProgressBar progBarPercent;
    // End of variables declaration//GEN-END:variables
}
