/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project75.jforms;

import com.project75.core.Semester;
import com.project75.core.Subject;
import com.project75.jpanels.AllSubjectPanel;
import com.formdev.flatlaf.*;

/**
 *
 * @author knovengel
 */
public class ApplicationFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ApplicationFrame.class.getName());

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame() {
        initComponents();
        Semester sem = createDummySemester(); // for now
        AllSubjectPanel allSubjectsPanel = new AllSubjectPanel(sem);

        scrollPaneAllSubjects.setViewportView(allSubjectsPanel);
        scrollPaneAllSubjects.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    private Semester createDummySemester() {
        Semester sem = new Semester(3, 5);

        Subject[] subs = sem.getSubs();
        subs[0] = new Subject("DSA", "Anand", "CE201");
        subs[1] = new Subject("DBMS", "Rupali", "CE202");
        subs[2] = new Subject("COA", "Yogita", "CE203");
        subs[3] = new Subject("DSGT", "Anuj", "CE204");
        subs[4] = new Subject("MS", "XYZ", "AS107");

    return sem;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneAllSubjects = new javax.swing.JScrollPane();
        scrollPaneMenu = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atendance Tracker");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneAllSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneAllSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(scrollPaneMenu))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatDarkLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ApplicationFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPaneAllSubjects;
    private javax.swing.JScrollPane scrollPaneMenu;
    // End of variables declaration//GEN-END:variables
}
